### ISSUE TITLE
Experimental keys on scalar is now forbidden at

### ISSUE THREAD

**Issue by entobento** [molevol-ub/DOMINO#4]
I have come across the "Experimental keys on scalar is now forbidden at <lines 2988, 3009, and 3028>" error in the DM_MarkerScan_V1.0.2.pl script.  I have corrected it by changing the code from
foreach <my $x (keys $y{$z}> to <foreach my $x (keys %{ $y{$z} }>   It seems to run okay but the script then fails throwing the error:

_ERROR: Can not open folder ... DOMINO/bin/lib/DOMINO.pm line 510._

The problem here seems to be that samtools 1.3.1 didn't fully install.  I install/make samtools version 1.3.1 and placed it in the DOMINO/bin file.  

Now it seems to run well... but it spits out this error no matter what parameters I use:

_+ Generate a BLAST database...
Generating the database failed when trying to proccess the file... DOMINO would not stop in this step...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! ERROR !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Early termination of the DOMINO Marker Scan...
Please note that DOMINO could not find any markers for the parameters provided. Please Re-Run DOMINO using other parameters_

To test and run DOMINO I'm using the 454 reads and the various input options specified below:
perl bin/DM_MarkerScan_v1.0.2_corr.pl -option DOMINO_files $HOMEDIR"201708311418_DM_assembly"  -o $HOMEDIR -type_input single_end -taxa_names Nemesia_sp043,N_raripilia061,N_raripilia079,I_brauni098 -VD 0.01 -CL 20::100 -VL 100::500 -CD 1 -DM discovery 

Is this latter error an actual error or a parameter input problem?

Thanks for any guidance,
Adam

**Comment by JFsanchezherrero** [comment]
Dear Adam,
Let's go one step at a time.

**Experimental keys on scalar is forbidden at...:**
I am afraid what you mention here is a problem due to the perl version o subversion at the moment of traversing the hash of hashes. I will try to check it out and fix it in further DOMINO versions.

**SAMTOOLS installation**
Sometimes some third party software included in DOMINO might fail during the installation and the thing is we are not dealing with it. It would definitely be really useful to include some kind of mini-test just to check everything is installed fine before running DOMINO. 

**DOMINO parameters**
I am afraid the error you can see here is due to the parameter configuration. I have to admit the example test files we use here are not fully profitable. They are real data from a set of markers we develop for another project, but sometimes, taking into account the parameters it might not provide markers.

I suggest you can use the simulated files we generated to test the efficiency and sensitivity of DOMINO which are under: DOMINO/example/simulated_data/

If you want to try with the real data you can set parameters to:  
-VD 0.01 -CL 40 -VL 400 -CD 1 -DM discovery -MCT 3: 
--> MCT: minimum covered taxa: it means at least 3 taxa would be fulfilling parameters.

-VD -1 -CL 40 -VL 400 -CD 1 -DM discovery
--> VD -1: it would retrieve any marker with a positive divergence (greater than 0)

I suggest you use a fix integer for the CL and VL parameters. We are working in the range set for these parameteres and we will be updating DOMINO soon.

Thank you very much for your interest, please contact me for any further questions.

Jose F. Sanchez

**Comment by entobento** [comment]
Thanks for this Jose!
Sadly the parameters you suggested for the real data didn't provide markers either...  I will try with the simulated data sets just to make sure.

As a side, I was under the impression (given the recent interactions with Guanlin) that parameter ranges were implimented in this version of DOMINO.  Is this not the case?

Though the assessment is running I am still getting some mapping errors, and uninitialized value warnings when trying to run the following code:

perl bin/DM_MarkerScan_v1.0.2_corr.pl -option DOMINO_files $HOMEDIR"201708311418_DM_assembly" -o $HOMEDIR -type_input single_end -taxa_names Nemesia_sp043,N_raripilia061,N_raripilia079,I_brauni098 -VD 0.01 -CL 40 -VL 400 -CD 1 -DM discovery -MCT 3:

Miscellaneous parameters:
	- Threads: 2
	- Deleting of temporary files would be done ...OK
	- DM mapping parameters details would be print into file:
		/cxfs/projects/fws/pifwo/avorsino/For_Super/DOMINO_test/201709071716_Mapping-Parameters.txt...
	- DM mapping errors occurred during the process would be print into file:
		/cxfs/projects/fws/pifwo/avorsino/For_Super/DOMINO_test/201709071716_Mapping_ERROR.txt...
	- DM markers parameters details would be print into file:
		/cxfs/projects/fws/pifwo/avorsino/For_Super/DOMINO_test/201709071716_Markers-Parameters.txt...
	- DM markers errors occurred during the process would be print into file:
		/cxfs/projects/fws/pifwo/avorsino/For_Super/DOMINO_test/201709071716_Markers_ERROR.txt...


[ Thu Sep  7 17:16:38 2017 ]	Step took 00 hours, 00 minutes, and 00 seconds

#################################################################################################
#################################### Mapping Process started ####################################
#################################################################################################


%%%%%%%%%%%%%%%%%%%%%%%%%%%% Get FASTQ files of the contigs generated %%%%%%%%%%%%%%%%%%%%%%%%%%%

+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++ Analysis of Molecular Markers started +++++++++++++++++++++++++++++
+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++


+ Markers Directory: /cxfs/projects/fws/pifwo/avorsino/For_Super/DOMINO_test/201709071716_DM_markers ...OK
[ Thu Sep  7 17:16:38 2017 ]	Step took 00 hours, 00 minutes, and 00 seconds



#################################################################################################
############################# Clustering markers for unique results #############################
#################################################################################################
+ Merging different DOMINO markers according to the taxa of reference...
Use of uninitialized value $coordinate_file in -s at bin/DM_MarkerScan_v1.0.2_corr.pl line 2685.
Use of uninitialized value $contig_file in -s at bin/DM_MarkerScan_v1.0.2_corr.pl line 2691.
Use of uninitialized value $coordinate_file in -s at bin/DM_MarkerScan_v1.0.2_corr.pl line 2685.
Use of uninitialized value $contig_file in -s at bin/DM_MarkerScan_v1.0.2_corr.pl line 2691.
Use of uninitialized value $coordinate_file in -s at bin/DM_MarkerScan_v1.0.2_corr.pl line 2685.
Use of uninitialized value $contig_file in -s at bin/DM_MarkerScan_v1.0.2_corr.pl line 2691.
Use of uninitialized value $coordinate_file in -s at bin/DM_MarkerScan_v1.0.2_corr.pl line 2685.
Use of uninitialized value $contig_file in -s at bin/DM_MarkerScan_v1.0.2_corr.pl line 2691.

**Comment by entobento** [comment]
Hi Jose,

So I tried it with your parameters and the simulated data... it looks like it worked pretty nicely (and super quickly).  I then tried it on my ezRAD data for a DENOVA alighnment of Nihoa Finch cleaned from a double end to a single end via ipyrad (again with your parameters).  No errors or warnings occured in either assessment.  Still working to get a better assessment using the ezRAD assessment though.  My understanding of it is that I can only use the msa files (.loci and alleles.loci) from ipyrad, and I can't run the data through the pipeline itself, is this correct?  Also, ipyrad generates two .loci files, .loci and .alleles.loci. , should I use one over the other?

I am going to close this as all the bugs have been ided and everything is working,

Best,

a
